### ISSUE TITLE
Crear pagina "¿Quienes somos?"

### ISSUE THREAD

**Issue by emirobles** [ISPC-Desarrolladores-2-0/PFS-Ecommerce-2023#12]
Debe tener información de la tienda e historia ficticia
Descripción del personal
Puede estar acompañado por imagenes
Las imagenes y locación que se emplean son de autoría propia, todos los derechos reservados.

**Debe ser responsive**

**Comment by MarcoVirinni** [comment]
Se desarrollo pagina sobre nosotros  "¿Quienes Somos?", con responsive basado en el sistema de columnas de Bootstrap. commit 4e20724
