### ISSUE TITLE
#H6 Crear pagina de "Contacto"

### ISSUE THREAD

**Issue by emirobles** [ISPC-Desarrolladores-2-0/PFS-Ecommerce-2023#13]
Debe tener un formulario de contacto solicitando como datos basicos: Nombre, telefono, mail y descripcion del mensaje.
Se pueden agregar otros campos para complementar.
Puede estar acompañado de la imagen de un mapa.

**Debe ser responsive**

**Comment by PaulaVelezz** [comment]
- [x] Maquetar sección en HTML.
- [x] Agregar estilos con CSS.
- [x] Diseño responsive.
- [x] Primera instancia de validación de datos/campos.
- [x] Integración de un iframe.
