### ISSUE TITLE
#H9 #H2 Crear  pagina de "Registro"

### ISSUE THREAD

**Issue by emirobles** [ISPC-Desarrolladores-2-0/PFS-Ecommerce-2023#15]
Esta pagina tendra un formulario para que el usuario pueda completar con sus datos personales.
Entre los datos esenciales se encuentran: Nombre, mail, telefono, dirección, clave.
Otros datos pueden ser incluidos para complementar el formulario
Boton: Registrarme

**Debe ser responsive**

**Comment by nico153** [comment]
cree la pagina registros con estructura html y estilos css
