### ISSUE TITLE
Arreglos después del testeo 

### ISSUE THREAD

**Issue by PaulaVelezz** [ISPC-Desarrolladores-2-0/PFS-Ecommerce-2023#27]
- [x] Navbar.
- [x] Footer. 
- [x] Formulario Contacto. 
- [x] Imagenes del carrusel.
- [x] Cards Details.
- [x] Cards efectos. 
- [x] Responsive.

**Comment by emirobles** [comment]
Arreglos completados en varios commits por los desarrolladores asignados.
commit ccc5b0c
commit 2cfaf30
commit 6307599
commit 4f7133a
commit a127cf9
commit 930e14e
commit b38c1ff
