### ISSUE TITLE
Desarrollar CRUD y métodos para "Categoría"

### ISSUE THREAD

**Issue by emirobles** [ISPC-Desarrolladores-2-0/PFS-Ecommerce-2023#36]
Agregar funcionalidades de gestión y operaciones esenciales a la clase Categoria para organizar los productos de la tienda de cómics.
Se requiere que se puedan filtrar los productos mediante las Categorias: Marvel y DC.
También que puedan enlistar todos los productos ordenados segun su categoria alfabeticamente.

**Comment by recursosssbb** [comment]
Para agregar funcionalidades de gestión de operaciones CRUD (Crear, Leer, Actualizar y Eliminar) a la clase Categoria y permitir la filtración

Primero       mysql-connector-python si aún no esta instalado:                                                                                                                con  **pip install mysql-connector-python**

**Comment by recursosssbb** [comment]
Esto instalará el paquete mysql-connector-pythonen el entorno Python, lo que te permitirá conectarte y trabajar con bases de datos MySQL en tu script.
