### ISSUE TITLE
Creación de sección "Reseñas"

### ISSUE THREAD

**Issue by emirobles** [ISPC-Desarrolladores-2-0/PFS-Ecommerce-2023#42]
Agregar una sección de reseñas en la página de inicio de la tienda de cómics para mostrar opiniones de clientes sobre los productos y/o la tienda.
Diseñar la apariencia y la ubicación de la sección de reseñas en la página de inicio utilizando HTML y Bootstrap.
Utilizar componentes de Bootstrap como tarjetas para mostrar las reseñas.
Aplicar estilos CSS para mejorar la apariencia de la sección de reseñas y asegurarse de que se integre con el diseño general de la página de inicio.
Utilizar Bootstrap para asegurarse de que la sección de reseñas sea responsive y se vea bien en diferentes dispositivos y tamaños de pantalla.

**Comment by duncanmartinez** [comment]
Realice reseña con HTML y style.css
